version: "3"
services:
  my-mongo:
    image: mongo:4.2.0
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=tut-04
      - MONGO_INITDB_ROOT_USERNAME=my-tut-04-root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./.data/db:/data/db
      - ./my-mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  my-mongo-express:
    image: mongo-express:0.49
    restart: always
    depends_on:
      - my-mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=my-mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=my-tut-04-root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    ports:
      - 8081:8081
  my-api:
    image: app-api:latest
    environment:
      - mongodb_url=mongodb://my-mongo/tut-04
      - mongodb_user=my-tut-04-user
      - mongodb_pass=password
    ports:
      - 3000:3000
  my-ui:
    image: app-ui:latest
    ports:
      - 80:80
